/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AsyncComponent1: typeof import('./src/components/asyncComponent1.vue')['default']
    AsyncComponent2: typeof import('./src/components/asyncComponent2.vue')['default']
    AsyncIframe: typeof import('./src/components/asyncIframe.vue')['default']
    BaseComponent: typeof import('./src/components/baseComponent.vue')['default']
    Child: typeof import('./src/components/child.vue')['default']
    ContentDemoItem: typeof import('./src/components/contentDemoItem.vue')['default']
    copy: typeof import('./src/components/asyncComponent1 copy.vue')['default']
    Father: typeof import('./src/components/Father.vue')['default']
    GenericsComponent: typeof import('./src/components/GenericsComponent.vue')['default']
    MouseTracker: typeof import('./src/components/MouseTracker.vue')['default']
    NullComp: typeof import('./src/components/nullComp.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Son: typeof import('./src/components/Son.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanCalendar: typeof import('vant/es')['Calendar']
    VanCell: typeof import('vant/es')['Cell']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanField: typeof import('vant/es')['Field']
    VanForm: typeof import('vant/es')['Form']
    VanPopup: typeof import('vant/es')['Popup']
  }
}
